[phases.setup]
nixPkgs = ["jdk17_headless"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["mvn package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/ai-deck-backend-0.0.1-SNAPSHOT.jar"